name: Deploy PHP app to Azure Web App - developer-costing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Ensures only the latest commit is fetched

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_323BEC9C0166495A8CB845162C31A8CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_973A9E58EEC24DADBAC2E56550A77210 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83502C707ED14856820D1B61A3DE8557 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'developer-costing'
          slot-name: 'Production'
          package: .

      - name: Restart Azure Web App
        run: az webapp restart --name 'developer-costing' --resource-group 'your-resource-group'
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_323BEC9C0166495A8CB845162C31A8CA }}
          AZURE_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_973A9E58EEC24DADBAC2E56550A77210 }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83502C707ED14856820D1B61A3DE8557 }}
          AZURE_PASSWORD: ${{ secrets.AZUREAPPSERVICE_PASSWORD }}
